apiVersion: apps/v1
kind: Deployment
metadata:
    name: centos-nodeport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: centos-nodeport
  template:
    metadata:
      labels:
        app: centos-nodeport
    spec:
      containers:
         - name: centos-nodeport
           image: rvegesna/centos:httpd1
---
apiVersion: v1
kind: Service
metadata:
  name: centos-nodeport
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 31100
  selector:
     app: r-nodeport
              
