apiVersion: apps/v1
kind: Deployment
metadata:
    name: r-app-service-clusterip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: r-app-service-clusterip
  template:
    metadata:
      labels:
        app: r-app-service-clusterip
    spec:
      containers:
         - name: image-service-clusterip
           image: rvegesna/centos:httpd1 
---
apiVersion: v1
kind: Service
metadata:
  name: r-ser-service-clusterip
spec:
  type: ClusterIP
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
  selector:
     run: r-ser-service-clusterip
              
