apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world1
  template:
    metadata:
      labels:
        app: hello-world1
    spec:
      nodeSelector:
         env: "test"
      containers:
      - name: hello-world1
        image: rvegesna/centos:httpd1
---
apiVersion: v1
kind: Service
metadata:
    name: hello-world1
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30070
  selector:
    app: hello-world1
